spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shootdb
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1  #服务器地址 你服务器或本机地址
      port: 6379           #连接端口
      database: 0          #数据库索引，默认0
      password:      #密码
  security:
    filter:
      order: -100
    jwt:
      key: sddasdasd
      expire: 7
server:
  port: 8080
file:
  upload:
    path: C://img/
    baseurl: http://localhost:8080/image/
